const express = require('express')

const app = express();

const port = process.env.Port || 8000;

const user = [
  {
    id: 1,
    name: "Alex Johnson",
    username: "alex1",
    email: "alex1@example.com",
    image: "https://i.pravatar.cc/150?img=1",
    role: "user",
    country: "USA",
  },
  {
    id: 2,
    name: "Sophia Williams",
    username: "sophia2",
    email: "sophia2@example.com",
    image: "https://i.pravatar.cc/150?img=2",
    role: "user",
    country: "Canada",
  },
  {
    id: 3,
    name: "Liam Brown",
    username: "liam3",
    email: "liam3@example.com",
    image: "https://i.pravatar.cc/150?img=3",
    role: "admin",
    country: "UK",
  },
  {
    id: 4,
    name: "Emma Davis",
    username: "emma4",
    email: "emma4@example.com",
    image: "https://i.pravatar.cc/150?img=4",
    role: "user",
    country: "Australia",
  },
  {
    id: 5,
    name: "Noah Wilson",
    username: "noah5",
    email: "noah5@example.com",
    image: "https://i.pravatar.cc/150?img=5",
    role: "user",
    country: "Germany",
  },
  {
    id: 6,
    name: "Olivia Miller",
    username: "olivia6",
    email: "olivia6@example.com",
    image: "https://i.pravatar.cc/150?img=6",
    role: "user",
    country: "France",
  },
  {
    id: 7,
    name: "James Taylor",
    username: "james7",
    email: "james7@example.com",
    image: "https://i.pravatar.cc/150?img=7",
    role: "user",
    country: "Japan",
  },
  {
    id: 8,
    name: "Ava Anderson",
    username: "ava8",
    email: "ava8@example.com",
    image: "https://i.pravatar.cc/150?img=8",
    role: "admin",
    country: "Bangladesh",
  },
  {
    id: 9,
    name: "William Thomas",
    username: "william9",
    email: "william9@example.com",
    image: "https://i.pravatar.cc/150?img=9",
    role: "user",
    country: "India",
  },
  {
    id: 10,
    name: "Isabella Moore",
    username: "isabella10",
    email: "isabella10@example.com",
    image: "https://i.pravatar.cc/150?img=10",
    role: "user",
    country: "Brazil",
  },
  {
    id: 11,
    name: "Benjamin White",
    username: "benjamin11",
    email: "benjamin11@example.com",
    image: "https://i.pravatar.cc/150?img=11",
    role: "user",
    country: "USA",
  },
  {
    id: 12,
    name: "Mia Harris",
    username: "mia12",
    email: "mia12@example.com",
    image: "https://i.pravatar.cc/150?img=12",
    role: "user",
    country: "Canada",
  },
  {
    id: 13,
    name: "Lucas Martin",
    username: "lucas13",
    email: "lucas13@example.com",
    image: "https://i.pravatar.cc/150?img=13",
    role: "admin",
    country: "UK",
  },
  {
    id: 14,
    name: "Charlotte Lee",
    username: "charlotte14",
    email: "charlotte14@example.com",
    image: "https://i.pravatar.cc/150?img=14",
    role: "user",
    country: "Australia",
  },
  {
    id: 15,
    name: "Henry Walker",
    username: "henry15",
    email: "henry15@example.com",
    image: "https://i.pravatar.cc/150?img=15",
    role: "user",
    country: "Germany",
  },
  {
    id: 16,
    name: "Amelia Hall",
    username: "amelia16",
    email: "amelia16@example.com",
    image: "https://i.pravatar.cc/150?img=16",
    role: "user",
    country: "France",
  },
  {
    id: 17,
    name: "Daniel Allen",
    username: "daniel17",
    email: "daniel17@example.com",
    image: "https://i.pravatar.cc/150?img=17",
    role: "user",
    country: "Japan",
  },
  {
    id: 18,
    name: "Harper Young",
    username: "harper18",
    email: "harper18@example.com",
    image: "https://i.pravatar.cc/150?img=18",
    role: "admin",
    country: "Bangladesh",
  },
  {
    id: 19,
    name: "Michael King",
    username: "michael19",
    email: "michael19@example.com",
    image: "https://i.pravatar.cc/150?img=19",
    role: "user",
    country: "India",
  },
  {
    id: 20,
    name: "Evelyn Scott",
    username: "evelyn20",
    email: "evelyn20@example.com",
    image: "https://i.pravatar.cc/150?img=20",
    role: "user",
    country: "Brazil",
  },
  {
    id: 21,
    name: "Jack Green",
    username: "jack21",
    email: "jack21@example.com",
    image: "https://i.pravatar.cc/150?img=21",
    role: "user",
    country: "USA",
  },
  {
    id: 22,
    name: "Ella Adams",
    username: "ella22",
    email: "ella22@example.com",
    image: "https://i.pravatar.cc/150?img=22",
    role: "user",
    country: "Canada",
  },
  {
    id: 23,
    name: "Logan Baker",
    username: "logan23",
    email: "logan23@example.com",
    image: "https://i.pravatar.cc/150?img=23",
    role: "admin",
    country: "UK",
  },
  {
    id: 24,
    name: "Grace Nelson",
    username: "grace24",
    email: "grace24@example.com",
    image: "https://i.pravatar.cc/150?img=24",
    role: "user",
    country: "Australia",
  },
  {
    id: 25,
    name: "David Carter",
    username: "david25",
    email: "david25@example.com",
    image: "https://i.pravatar.cc/150?img=25",
    role: "user",
    country: "Germany",
  },
  {
    id: 26,
    name: "Chloe Mitchell",
    username: "chloe26",
    email: "chloe26@example.com",
    image: "https://i.pravatar.cc/150?img=26",
    role: "user",
    country: "France",
  },
  {
    id: 27,
    name: "Matthew Perez",
    username: "matthew27",
    email: "matthew27@example.com",
    image: "https://i.pravatar.cc/150?img=27",
    role: "admin",
    country: "Japan",
  },
  {
    id: 28,
    name: "Lily Roberts",
    username: "lily28",
    email: "lily28@example.com",
    image: "https://i.pravatar.cc/150?img=28",
    role: "user",
    country: "Bangladesh",
  },
  {
    id: 29,
    name: "Joseph Turner",
    username: "joseph29",
    email: "joseph29@example.com",
    image: "https://i.pravatar.cc/150?img=29",
    role: "user",
    country: "India",
  },
  {
    id: 30,
    name: "Zoey Phillips",
    username: "zoey30",
    email: "zoey30@example.com",
    image: "https://i.pravatar.cc/150?img=30",
    role: "user",
    country: "Brazil",
  },
  {
    id: 31,
    name: "Andrew Campbell",
    username: "andrew31",
    email: "andrew31@example.com",
    image: "https://i.pravatar.cc/150?img=31",
    role: "user",
    country: "USA",
  },
  {
    id: 32,
    name: "Scarlett Parker",
    username: "scarlett32",
    email: "scarlett32@example.com",
    image: "https://i.pravatar.cc/150?img=32",
    role: "admin",
    country: "Canada",
  },
  {
    id: 33,
    name: "Christopher Evans",
    username: "christopher33",
    email: "christopher33@example.com",
    image: "https://i.pravatar.cc/150?img=33",
    role: "user",
    country: "UK",
  },
  {
    id: 34,
    name: "Victoria Edwards",
    username: "victoria34",
    email: "victoria34@example.com",
    image: "https://i.pravatar.cc/150?img=34",
    role: "user",
    country: "Australia",
  },
  {
    id: 35,
    name: "Samuel Collins",
    username: "samuel35",
    email: "samuel35@example.com",
    image: "https://i.pravatar.cc/150?img=35",
    role: "user",
    country: "Germany",
  },
  {
    id: 36,
    name: "Hannah Stewart",
    username: "hannah36",
    email: "hannah36@example.com",
    image: "https://i.pravatar.cc/150?img=36",
    role: "admin",
    country: "France",
  },
  {
    id: 37,
    name: "Nathan Morris",
    username: "nathan37",
    email: "nathan37@example.com",
    image: "https://i.pravatar.cc/150?img=37",
    role: "user",
    country: "Japan",
  },
  {
    id: 38,
    name: "Aria Rogers",
    username: "aria38",
    email: "aria38@example.com",
    image: "https://i.pravatar.cc/150?img=38",
    role: "user",
    country: "Bangladesh",
  },
  {
    id: 39,
    name: "Ryan Reed",
    username: "ryan39",
    email: "ryan39@example.com",
    image: "https://i.pravatar.cc/150?img=39",
    role: "user",
    country: "India",
  },
  {
    id: 40,
    name: "Aurora Cook",
    username: "aurora40",
    email: "aurora40@example.com",
    image: "https://i.pravatar.cc/150?img=40",
    role: "admin",
    country: "Brazil",
  },
  {
    id: 41,
    name: "Isaac Morgan",
    username: "isaac41",
    email: "isaac41@example.com",
    image: "https://i.pravatar.cc/150?img=41",
    role: "user",
    country: "USA",
  },
  {
    id: 42,
    name: "Layla Bell",
    username: "layla42",
    email: "layla42@example.com",
    image: "https://i.pravatar.cc/150?img=42",
    role: "user",
    country: "Canada",
  },
  {
    id: 43,
    name: "Gabriel Murphy",
    username: "gabriel43",
    email: "gabriel43@example.com",
    image: "https://i.pravatar.cc/150?img=43",
    role: "admin",
    country: "UK",
  },
  {
    id: 44,
    name: "Penelope Bailey",
    username: "penelope44",
    email: "penelope44@example.com",
    image: "https://i.pravatar.cc/150?img=44",
    role: "user",
    country: "Australia",
  },
  {
    id: 45,
    name: "Anthony Rivera",
    username: "anthony45",
    email: "anthony45@example.com",
    image: "https://i.pravatar.cc/150?img=45",
    role: "user",
    country: "Germany",
  },
  {
    id: 46,
    name: "Natalie Cooper",
    username: "natalie46",
    email: "natalie46@example.com",
    image: "https://i.pravatar.cc/150?img=46",
    role: "user",
    country: "France",
  },
  {
    id: 47,
    name: "Dylan Richardson",
    username: "dylan47",
    email: "dylan47@example.com",
    image: "https://i.pravatar.cc/150?img=47",
    role: "admin",
    country: "Japan",
  },
  {
    id: 48,
    name: "Lucy Cox",
    username: "lucy48",
    email: "lucy48@example.com",
    image: "https://i.pravatar.cc/150?img=48",
    role: "user",
    country: "Bangladesh",
  },
  {
    id: 49,
    name: "Owen Ward",
    username: "owen49",
    email: "owen49@example.com",
    image: "https://i.pravatar.cc/150?img=49",
    role: "user",
    country: "India",
  },
  {
    id: 50,
    name: "Stella Brooks",
    username: "stella50",
    email: "stella50@example.com",
    image: "https://i.pravatar.cc/150?img=50",
    role: "user",
    country: "Brazil",
  },
];



app.get('/', (req, res) => {
    res.send('hello');
})


app.get('/user', (req, res) => {
    res.send(user);
})

app.post('/user', (req, res) => {
    res.send(user);
})


app.listen(port, () => {
    console.log("server is running")
})